# Generated by Django 5.0.6 on 2024-06-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_generator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ProductName", models.CharField(max_length=30)),
                ("ProductHSNCode", models.CharField(max_length=30)),
            ],
        ),
    ]
