# Generated by Django 5.0.6 on 2024-07-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_generator", "0003_alter_customer_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CustomerName", models.CharField(max_length=100)),
                ("InvoiceDate", models.DateField()),
                ("InvoiceDescription", models.JSONField(default=dict)),
                ("InvoiceTotal", models.IntegerField()),
                ("InvoiceFile", models.FileField(upload_to="invoices")),
                ("InvoiceStatus", models.CharField(default="Unpaid", max_length=25)),
                ("PaymentMethod", models.CharField(max_length=50, null=True)),
                ("CreatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
