# Generated by Django 5.0.6 on 2024-07-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_generator", "0004_invoicedata"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicedata",
            name="InvoiceNumber",
            field=models.IntegerField(default=63),
            preserve_default=False,
        ),
    ]
