# Generated by Django 5.0.6 on 2024-07-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_generator", "0006_alter_customer_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="PhoneNumber",
            field=models.IntegerField(),
        ),
    ]
