# Generated by Django 5.0.6 on 2024-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_generator", "0007_alter_customer_phonenumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("InvoiceNumber", models.IntegerField()),
                ("Action", models.CharField(max_length=1000)),
                ("Date", models.DateField(auto_now=True)),
                ("Time", models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="customer",
            name="PhoneNumber",
            field=models.BigIntegerField(),
        ),
    ]
