# Generated by Django 5.0.6 on 2024-07-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_generator", "0008_recentactivity_alter_customer_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicedata",
            name="InvoiceFile",
            field=models.CharField(max_length=100),
        ),
    ]
