# Generated by Django 5.0.6 on 2025-02-11 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice_generator", "0009_alter_invoicedata_invoicefile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicedata",
            name="InvoiceFile",
        ),
    ]
